### ISSUE TITLE
6750Gre是否有啸叫声，性能损失如何

### ISSUE THREAD

**Issue by xinghengYu** [TaiJi2022/H610m-12400f-6750gre#1]
大佬，问一下。
我这边也有一台6750gre的黑苹果。
但是我切到mac下显卡的啸叫声就挺明显的，回windows就基本没有。
另外感觉显卡的性能损失挺大的，geekbench或者cinebench跑分时，用活动监视器里看到的gpu占用率都跑不满，感觉只有20%。
您那边有这些情况么。

**Comment by TaiJi2022** [comment]
没有上述情况哦
